spring:
  data:
    mongodb:
      host: 172.31.250.34
      port: 27017
      database: tparchi
  rabbitmq:
    host: localhost
    port: 5672

logging:
  level:
    org: ERROR

server:
  port: 8081
