version: '3.9'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
          - 6550:80
        volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - /data/log/nginx:/var/log/nginx
